#This Travis config template file was taken from https://github.com/FriendsOfCake/travis
language: php

php:
  - 5.6
  - 7.0

sudo: false

env:
  matrix:
    - DB=mysql db_dsn='mysql://travis@0.0.0.0/cakephp_test'
  global:
    - DEFAULT=1

matrix:
  fast_finish: true

install:
  - composer install --no-interaction --no-progress --no-suggest
  - mkdir -p build/logs

before_script:
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'CREATE DATABASE cakephp_test;'; fi"

script:
  - vendor/bin/phpunit
  - vendor/bin/phpcs

after_success:
  - curl -s https://codecov.io/bash > /tmp/codecov.sh
  - chmod +x /tmp/codecov.sh
  - /tmp/codecov.sh -s build/logs

notifications:
  email:
    - webdev@qobocloud.com
